#Alerts cron scheduler expression
qa.cron.expression.generate.alerts = -

#sending alert mails every Monday
#qa.cron.expression.sending.alert.mails = -

#sending alert mails every day based on alert_type
qa.cron.expression.sending.alert.mails.by.alert.type = -

#User login timeout
qa.cron.expression.user.login.timeout = -

#send issues every month 
qa.cron.expression.send.mail.with.open.issues =  -

#send contract.bg.insurance.report 
qa.cron.expression.send.mail.with.contract.bg.insurance.report = -

#sending user login report mail
qa.cron.expression.sending.user.login.report.mails = -

#generate assign responsibility
qa.cron.expression.generate.assign.responsibility = -