qa.cron.expression.generate.alerts = -

qa.cron.expression.sending.alert.mails.by.alert.type = -

qa.cron.expression.user.login.timeout = -

qa.cron.expression.send.mail.with.open.issues = -

qa.cron.expression.send.mail.with.contract.bg.insurance.report = -

qa.cron.expression.sending.user.login.report.mails = -

qa.cron.expression.generate.assign.responsibility = -