#Alerts cron scheduler expression at 1:10 AM everyday
qa.cron.expression.generate.alerts = -

#sending alert mails every Monday at 3:30 AM 
#qa.cron.expression.sending.alert.mails = -

#sending alert mails every day based on alert_type at 1:45 AM 
qa.cron.expression.sending.alert.mails.by.alert.type = -

#User login timeout every 30 minutes 
qa.cron.expression.user.login.timeout = -

#send issues every month 1st and 15th dates at 3 AM 
qa.cron.expression.send.mail.with.open.issues =  -

#send contract.bg.insurance.report every month 1st and 16th dates at 2:45 AM 
qa.cron.expression.send.mail.with.contract.bg.insurance.report = -

#sending user login report mail every Monday at 12:10 AM 
qa.cron.expression.sending.user.login.report.mails = -

#generate assign responsibility at 12:30 AM everyday
qa.cron.expression.generate.assign.responsibility = -