
# Local or QA Database = WRPMISQA_DB 
# Production Database = WRPMIS_DB

db.environment = WRPMIS_DB


# Local or QA ==> false
# Production ==>  true
run.cron.jobs = false

# Local ==> false
# QA ==> true
# Production ==> false
run.cron.jobs.in.qa = false


