Login.Form.Header = Driving Infrastructure Forward
Logout.Message = Successfully logged out

Login.Form.Invalid = Invalid username and password.

no.pmis.form.Key = Please Contact Admin For Access

common.error.message = Oops! Something went wrong! Please try again.

#password 
message.password.expired = Your password is expired. Please reset here.
message.password.reset.fail = Reset password failed.
message.password.reset.success = Your Password has been changed successfully.
message.wrong.password.entered = You have entered wrong old password.
